web:
  image: grzegorzwodo/seqr-ecommerce-base:PHP5_6
  ports:
    - "8080:80"
    - "13306:3306"
  volumes_from:
    - web-data
  links:
    - ftp
ftp:
  image: damienlagae/ftp
  volumes_from:
    - web-data
web-data:
  image: grzegorzwodo/ecommerce-opencart-data
  environment:
    PLUGIN_NAME: 'seqr'
    OC_VERSION: '2.1.0.1'
  volumes:
    - ./admin:/var/www/html/plugin/seqr/admin
    - ./catalog:/var/www/html/plugin/seqr/catalog
    - ./admin/controller/payment/seqr.php:/var/www/html/upload/admin/controller/payment/seqr.php
    - ./admin/language/english/payment/seqr.php:/var/www/html/upload/admin/language/english/payment/seqr.php
    - ./admin/view/template/payment/seqr.tpl:/var/www/html/upload/admin/view/template/payment/seqr.tpl
    - ./catalog/controller/payment/seqr.php:/var/www/html/upload/catalog/controller/payment/seqr.php
    - ./catalog/language/english/payment/seqr.php:/var/www/html/upload/catalog/language/english/payment/seqr.php
    - ./catalog/model/payment/seqr.php:/var/www/html/upload/catalog/model/payment/seqr.php
    - ./catalog/model/payment/seqr_api.php:/var/www/html/upload/catalog/model/payment/seqr_api.php
    - ./catalog/view/theme/default/template/payment/seqr.tpl:/var/www/html/upload/catalog/view/theme/default/template/payment/seqr.tpl
    - ./admin/controller/payment/seqr_refund.php:/var/www/html/upload/admin/controller/payment/seqr_refund.php
    - ./admin/view/template/payment/seqr_refund.tpl:/var/www/html/upload/admin/view/template/payment/seqr_refund.tpl
    - ./admin/language/english/payment/seqr_refund.php:/var/www/html/upload/admin/language/english/payment/seqr_refund.php
    - ./admin/model/payment/seqr_refund.php:/var/www/html/upload/admin/model/payment/seqr_refund.php
    - ./admin/model/payment/seqr_api.php:/var/www/html/upload/admin/model/payment/seqr_api.php
